// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsv-PHGlBOf11oD4cxh2BBD9bar1JIluM',
    appId: '1:148963456311:web:fb147d6c9de98dc58b16b2',
    messagingSenderId: '148963456311',
    projectId: 'ichatty-71ab4',
    authDomain: 'ichatty-71ab4.firebaseapp.com',
    storageBucket: 'ichatty-71ab4.appspot.com',
    measurementId: 'G-H90QVJFJYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOHV4-OtilSC5ju6ITBuSRarJqdVvaF1w',
    appId: '1:148963456311:android:caae891b372ce2718b16b2',
    messagingSenderId: '148963456311',
    projectId: 'ichatty-71ab4',
    storageBucket: 'ichatty-71ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFF5v-nAoFKXjZhOMbIliJCJu39VfELc',
    appId: '1:148963456311:ios:f0109d65a59442fb8b16b2',
    messagingSenderId: '148963456311',
    projectId: 'ichatty-71ab4',
    storageBucket: 'ichatty-71ab4.appspot.com',
    iosClientId: '148963456311-k3voqhhsh9achai50cs1r7gbs50a3glu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichatty',
  );
}
